CRUD.Web/Models/CadastroViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace CRUD.Web.Models
{
    public class CadastroViewModel
    {
        public long Id { get; set; }

        public string NomeCompleto { get; set; }

        public string Email { get; set; }

        public string Telefone { get; set; }
    }
}

CRUD.Web/Controllers/CadastroController.cs
using CRUD.Web.Models;
using Newtonsoft.Json;
using RestSharp;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Text;
using System.Web;
using System.Web.Mvc;

namespace CRUD.Web.Controllers
{
    public class CadastroController : Controller
    {
        #region Read
        // GET: Read
        public ActionResult Read()
        {
            var client = new RestClient("http://localhost:7307/api/cadastro");

            var response = client.Execute(new RestRequest());

            var modelList = JsonConvert.DeserializeObject<List<CadastroViewModel>>(response.Content);

            return View(modelList);
        }
        #endregion

        #region Create
        // GET: Create
        [HttpGet]
        public ActionResult Create()
        {
            var model = new CadastroViewModel();

            return View(model);
        }
        

        // Post: Create
        [HttpPost]
        public ActionResult Create(CadastroViewModel cadastro)
        {
            var client = new RestClient("http://localhost:7307/api/cadastro");
            var request = new RestRequest(Method.POST);

            var jsonCadastro = JsonConvert.SerializeObject(cadastro);

            request.AddHeader("content-type", "application/json");
            request.AddParameter("application/json; charset=utf-8", jsonCadastro, ParameterType.RequestBody);

            var response = client.Execute(request);

            return RedirectToAction("Read");
        }
        #endregion

        #region Delete
        // GET: Delete
        [HttpGet]
        public ActionResult Delete(long id)
        {
            var client = new RestClient("http://localhost:7307/api/cadastro/"+id);

            var response = client.Execute(new RestRequest());

            var modelList = JsonConvert.DeserializeObject<CadastroViewModel>(response.Content);

            return View(modelList);
        }

        // Post: Delete
        [HttpPost]
        public ActionResult Delete(CadastroViewModel cadastro)
        {
            var client = new RestClient("http://localhost:7307/api/cadastro/" + cadastro.Id);
            var request = new RestRequest(Method.DELETE);
            
            var response = client.Execute(request);

            return RedirectToAction("Read");
        }
        #endregion

        #region Update
        // GET: Update
        [HttpGet]
        public ActionResult Update(long id)
        {
            var client = new RestClient("http://localhost:7307/api/cadastro/" + id);

            var response = client.Execute(new RestRequest());

            var modelList = JsonConvert.DeserializeObject<CadastroViewModel>(response.Content);

            return View(modelList);
        }

        // Post: Update
        [HttpPost]
        public ActionResult Update(CadastroViewModel cadastro)
        {
            var client = new RestClient("http://localhost:7307/api/cadastro");
            var request = new RestRequest(Method.PUT);
            var jsonCadastro = JsonConvert.SerializeObject(cadastro);

            request.AddHeader("content-type", "application/json");
            request.AddParameter("application/json; charset=utf-8", jsonCadastro, ParameterType.RequestBody);

            var response = client.Execute(request);

            return RedirectToAction("Read");
        }
        #endregion
    }
}

CRUD.Web/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace CRUD.Web.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }
    }
}

CRUD.Web/Views/Cadastro/Create.cshtml
@model  CRUD.Web.Models.CadastroViewModel

@{
    ViewBag.Title = "Save";
}

<div style="margin-top:20px;">

    @using (Html.BeginForm("Create", "Cadastro", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="form-group">
            <label for="exampleInputEmail1">Nome Completo:</label>
            @Html.EditorFor(model => model.NomeCompleto, new { htmlAttributes = new { @required = "required", @class = "form-control" } })
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Endereço de email</label>
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @type = "email", @required = "required", @class = "form-control" } })
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Telefone:</label>
            @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @required = "required", @class = "form-control" } })
        </div>

        <input type="submit" class="btn-success" value="Enviar">
    
    }
</div>

CRUD.Web/Views/Cadastro/Delete.cshtml
@model  CRUD.Web.Models.CadastroViewModel

@{
    ViewBag.Title = "Delete";
}

<div style="margin-top:20px;">

    @using (Html.BeginForm("Delete", "Cadastro", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="form-group">
            <label for="exampleInputEmail1">Nome Completo:</label>
            @Html.EditorFor(model => model.NomeCompleto, new { htmlAttributes = new { @class = "form-control" } })
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Endereço de email</label>
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Telefone:</label>
            @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
        </div>

        <input type="submit" class="btn-success" value="Enviar">
    
    }
</div>

CRUD.Web/Views/Cadastro/Read.cshtml
@model  IEnumerable<CRUD.Web.Models.CadastroViewModel>

<table class="table table-bordered table-hover" style="margin-top:20px;" id="tableListaDePresenca">
    <thead>
        <tr>
            <th>
                ID
            </th>
            <th>
                Nome Completo
            </th>
            <th>
                Email
            </th>
            <th>
                Telefone
            </th>
            <th>
                Ações
            </th>
        </tr>
    </thead>

    <tbody>
        @foreach (var item in Model.ToList())
        {
        <tr>
            <td style="vertical-align: middle">
                @Html.DisplayFor(modelItem => item.Id)
            </td>
            <td style="vertical-align: middle">
                @Html.DisplayFor(modelItem => item.NomeCompleto)
            </td>
            <td style="vertical-align: middle">
                @Html.DisplayFor(modelItem => item.Email)
            </td>
            <td style="vertical-align: middle">
                @Html.DisplayFor(modelItem => item.Telefone)
            </td>
            <td style="vertical-align: middle">
                
                @Html.ActionLink(" ", "Create", "Cadastro",  new { @class = "btn btn-xs btn-primary glyphicon glyphicon-plus" })
                @Html.ActionLink(" ", "Update", "Cadastro", new { id = item.Id }, new { @class = "btn btn-xs btn-warning glyphicon glyphicon-pencil" })
                @Html.ActionLink(" ", "Delete", "Cadastro", new { id = item.Id }, new { @class = "btn btn-xs btn-danger glyphicon glyphicon-minus" })
            </td>
        </tr>
        }
    </tbody>

</table>

CRUD.Web/Views/Cadastro/Update.cshtml
@model  CRUD.Web.Models.CadastroViewModel

@{
    ViewBag.Title = "Update";
}

<div style="margin-top:20px;">

    @using (Html.BeginForm("Update", "Cadastro", FormMethod.Post))
    {
        @Html.AntiForgeryToken()
        <div class="form-group">
            <label for="exampleInputEmail1">Nome Completo:</label>
            @Html.EditorFor(model => model.NomeCompleto, new { htmlAttributes = new { @class = "form-control" } })
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Endereço de email</label>
            @Html.EditorFor(model => model.Email, new { htmlAttributes = new { @class = "form-control" } })
        </div>
        <div class="form-group">
            <label for="exampleInputEmail1">Telefone:</label>
            @Html.EditorFor(model => model.Telefone, new { htmlAttributes = new { @class = "form-control" } })
        </div>

        <input type="submit" class="btn-success" value="Enviar">
    
    }
</div>

CRUD.Web/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

CRUD.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("Cadastro", "Read", "Cadastro")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>